

build-cc7:
  tags:
    - cvmfs
  image: alisw/alidock:cc7
  stage: build
  variables:
    GIT_CLONE_PATH: '$CI_BUILDS_DIR/FairShip/'
  before_script:
    - source /cvmfs/ship.cern.ch/2_July2019/setUp.sh
    - git clone https://github.com/siscia/shipdist
    - pushd shipdist && git checkout simple_build && popd
  script:
    - aliBuild -c shipdist/ --default fairship build FairShip --always-prefer-system --debug
  artifacts:
    paths:
      - sw/
    expire_in: 1 week

test-cc7:
  tags:
    - cvmfs
  image: alisw/alidock:cc7
  stage: test
  variables:
    GIT_CLONE_PATH: '$CI_BUILDS_DIR/FairShip/'
  before_script:
    - source /cvmfs/ship.cern.ch/2_July2019/setUp.sh
    - eval `alienv load FairShip/latest-fairship`
  script:
    - python $FAIRSHIP/macro/run_simScript.py --test
    - python $FAIRSHIP/macro/ShipReco.py -f ship.conical.Pythia8-TGeant4.root -g geofile_full.conical.Pythia8-TGeant4.root
    - python $FAIRSHIP/macro/ShipAna.py -f ship.conical.Pythia8-TGeant4_rec.root -g geofile_full.conical.Pythia8-TGeant4.root

