
build-cc7:
  tags:
    - cvmfs
  image: alisw/alidock:cc7
  stage: build
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/FairShip/1
  before_script:
    - WORK_DIR=/cvmfs/ship.cern.ch/2_July2019/sw/ source /cvmfs/ship.cern.ch/2_July2019/sw/slc7_x86-64/FairShip/latest/etc/profile.d/init.sh
    - pip install --upgrade --user alibuild
    - ls /cvmfs/ship.cern.ch
    - git clone https://github.com/siscia/shipdist
    - pushd shipdist && git checkout simple_build && popd
    - env
  script:
    - aliBuild -c shipdist/ --default fairship build FairShip --always-prefer-system --debug
    - echo sw
  artifacts:
    paths:
      - sw
    expire_in: 1 week

test-cc7:
  tags:
    - cvmfs
  image: alisw/alidock:cc7
  stage: test
  before_script:
    - cd ..
    - WORK_DIR=/cvmfs/ship.cern.ch/2_July2019/sw/ source /cvmfs/ship.cern.ch/2_July2019/sw/slc7_x86-64/FairShip/latest/etc/profile.d/init.sh
    - pip install --upgrade --user alibuild
    - alienv enter FairShip/latest
  script:
    - python $FAIRSHIP/macro/run_simScript.py --test
    - python $FAIRSHIP/macro/ShipReco.py -f ship.conical.Pythia8-TGeant4.root -g geofile_full.conical.Pythia8-TGeant4.root
    - python -i $FAIRSHIP/macro/ShipAna.py -f ship.conical.Pythia8-TGeant4_rec.root -g geofile_full.conical.Pythia8-TGeant4.root
  artifacts:
    paths:
      - sw
    expire_in: 1 week

